my:
  greeting: Hello world from config server
  list:
    values: one, two, three, four
spring:
  cloud:
    config:
      server:
        native:                      
          searchLocations: classpath:/config          
server:
  port: 8888
