my:
  greeting: Hello!! marslin vijay!!, welcome to the world of spring
  list:
    values: one, two, three, four
spring:
  cloud:
    config:
      server:
        native:                      
          searchLocations: classpath:/config          
server:
  port: 8888

spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
